[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Disable all framework auto-detection
[[plugins]]
  package = "@netlify/plugin-gatsby" # dummy plugin to override auto-detection
  pinned_version = "4.0.0"
  [plugins.inputs]
  enable = false
